In [1]:
# Import dependencies
import pandas as pd

In [3]:
# Data source: https://www.kaggle.com/rounakbanik/pokemon

pokemon_df = pd.read_csv("pokemon.csv")
pokemon_df.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [4]:
# Drop the columns we don't care about

pokemon_ordered = pokemon_df.drop(columns={"base_egg_steps", "base_happiness", "base_total", "capture_rate", 
                                           "experience_growth", "japanese_name"})
pokemon_ordered.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [5]:
# Set index to pokedex number
pokemon_ordered = pokemon_ordered.set_index("pokedex_number")
pokemon_ordered.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,name,percentage_male,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
pokedex_number,,,,,,,,,,,,,,,,,,,,,
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,Bulbasaur,88.1,65,65,45,grass,poison,6.9,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,Ivysaur,88.1,80,80,60,grass,poison,13.0,1,0
3,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,Venusaur,88.1,122,120,80,grass,poison,100.0,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,Charmander,88.1,60,50,65,fire,NaN,8.5,1,0
5,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,Charmeleon,88.1,80,65,80,fire,NaN,19.0,1,0

In [11]:
# Make dataframe just for pokemon info
pokemon_info = pokemon_ordered[["name", "generation", "classfication", "type1", "type2", "hp", "height_m",
                                "weight_kg", "speed", "percentage_male", "is_legendary"]]
pokemon_info.head()

,name,generation,classfication,type1,type2,hp,height_m,weight_kg,speed,percentage_male,is_legendary
pokedex_number,,,,,,,,,,,
1,Bulbasaur,1,Seed PokÃ©mon,grass,poison,45,0.7,6.9,45,88.1,0
2,Ivysaur,1,Seed PokÃ©mon,grass,poison,60,1.0,13.0,60,88.1,0
3,Venusaur,1,Seed PokÃ©mon,grass,poison,80,2.0,100.0,80,88.1,0
4,Charmander,1,Lizard PokÃ©mon,fire,NaN,39,0.6,8.5,65,88.1,0
5,Charmeleon,1,Flame PokÃ©mon,fire,NaN,58,1.1,19.0,80,88.1,0

In [10]:
# Make datafram for battle info
pokemon_battle_info = pokemon_ordered[["attack", "defense", "sp_attack", "sp_defense", "abilities", "against_bug", 
                                       "against_dark", "against_dragon", "against_electric", "against_fairy", 
                                       "against_fight", "against_fire", "against_flying", "against_ghost", 
                                       "against_grass", "against_ground", "against_ice", "against_normal", 
                                       "against_poison", "against_psychic", "against_rock", "against_steel", 
                                       "against_water"]]
pokemon_battle_info.head()

,attack,defense,sp_attack,sp_defense,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,...,against_ghost,against_grass,against_ground,against_ice,against_normal,against_poison,against_psychic,against_rock,against_steel,against_water
pokedex_number,,,,,,,,,,,,,,,,,,,,,
1,49,49,65,65,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,...,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5
2,62,63,80,80,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,...,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5
3,100,123,122,120,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,...,1.0,0.25,1.0,2.0,1.0,1.0,2.0,1.0,1.0,0.5
4,52,43,60,50,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,...,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0
5,64,58,80,65,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,...,1.0,0.50,2.0,0.5,1.0,1.0,1.0,2.0,0.5,2.0